name: even
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.30.0
  firebase_core_web: ^2.12.1
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_auth_web: ^5.8.13
  firebase_analytics: ^10.8.0
  provider: ^6.0.0
  intl: ^0.18.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
