// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwlY_cfk7JLwp92j50FHYiOmhAuP2T2Q',
    appId: '1:619279764224:web:8712a62fd640647fb941e5',
    messagingSenderId: '619279764224',
    projectId: 'even-76b1d',
    authDomain: 'even-76b1d.firebaseapp.com',
    storageBucket: 'even-76b1d.firebasestorage.app',
    measurementId: 'G-S7VHE1MZSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCob1C5647d8zxPT4g2Lhwu9L8lqZHTf88',
    appId: '1:619279764224:android:8d3a5780935dc828b941e5',
    messagingSenderId: '619279764224',
    projectId: 'even-76b1d',
    storageBucket: 'even-76b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpyV40_0CR4HBCp94b2Tlq9sdm_BtgTY',
    appId: '1:619279764224:ios:945e21a644776bb8b941e5',
    messagingSenderId: '619279764224',
    projectId: 'even-76b1d',
    storageBucket: 'even-76b1d.firebasestorage.app',
    iosBundleId: 'com.example.even',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpyV40_0CR4HBCp94b2Tlq9sdm_BtgTY',
    appId: '1:619279764224:ios:945e21a644776bb8b941e5',
    messagingSenderId: '619279764224',
    projectId: 'even-76b1d',
    storageBucket: 'even-76b1d.firebasestorage.app',
    iosBundleId: 'com.example.even',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwlY_cfk7JLwp92j50FHYiOmhAuP2T2Q',
    appId: '1:619279764224:web:d3e15f8048931a59b941e5',
    messagingSenderId: '619279764224',
    projectId: 'even-76b1d',
    authDomain: 'even-76b1d.firebaseapp.com',
    storageBucket: 'even-76b1d.firebasestorage.app',
    measurementId: 'G-4T1W4Q59GL',
  );
}
